const ImgComp=()=>{
    return (
        <img 
        style={{
            width:"100px",
            height:"100px",
            borderRadius:"50%",
            objectFit:"cover",
            margin:"10px"
        }}
        src={"https://picsum.photos/200"}/>
    )
}
const Home=()=>{
    return(
        <>
            <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rerum, dignissimos. Ratione aliquid sed suscipit doloremque illum delectus praesentium officiis veritatis vero, eaque modi voluptates vitae! Nemo voluptas voluptatem, quaerat sed sapiente molestias temporibus quisquam! Cumque nisi at magni repellendus laborum amet officia autem suscipit? Deleniti amet est aut excepturi unde saepe quasi laboriosam, recusandae eum iste accusamus quod ipsum animi totam a in inventore nulla voluptas cum nemo accusantium. Incidunt nobis veniam officia nisi impedit dolores sint, quas, accusantium fugiat facere laudantium quis atque possimus animi quasi libero assumenda voluptatum aspernatur soluta laborum deserunt. Velit provident expedita cumque distinctio quam illum suscipit, quos sint. Dicta natus hic laborum maiores a unde voluptas aspernatur soluta maxime aliquid nobis, facere mollitia officia, sed iure illum ea voluptatum porro. Sequi dolores esse doloremque placeat mollitia ipsum expedita minus vitae, amet neque cum assumenda, accusamus nostrum officia tempora officiis possimus repellendus? Dolor eveniet non dolorum illo placeat repellendus vitae cum delectus maxime voluptatem ex totam quod sed reprehenderit animi esse explicabo labore, excepturi nulla rem facere sapiente sit, quas odit. Enim nobis necessitatibus sint soluta quod reiciendis itaque voluptatem vero reprehenderit, cupiditate fuga. Cumque obcaecati facilis, deserunt ipsum ut placeat reprehenderit vero assumenda rerum.</h3>
            <ImgComp/>
            <h3>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, excepturi explicabo nisi ex sunt repellendus possimus veritatis quibusdam, officia ducimus id pariatur natus quidem modi perferendis. Nostrum error quas possimus obcaecati rem, dignissimos odio modi a debitis nemo tenetur vitae fuga. Dolor placeat assumenda provident temporibus voluptate laborum repellat illo, pariatur cumque. Cum, expedita hic fugiat provident dolores ipsa veniam consequatur soluta libero nostrum mollitia asperiores dolorem, nemo quaerat nam velit ex obcaecati? Ipsa animi dolorem veniam quia molestiae modi quisquam natus. Inventore maiores adipisci optio, officiis illum fugiat in eum possimus tempora dolores vel? Assumenda, nihil! Reprehenderit perspiciatis dicta eum quam. Maiores nesciunt, ratione, dolores quae aperiam velit debitis nulla necessitatibus sequi repudiandae quidem magni nostrum eveniet ut quasi ab, quia recusandae provident est? Minus itaque quisquam praesentium vero corrupti, ipsum distinctio quaerat nesciunt corporis modi ducimus atque non consequuntur soluta earum mollitia in asperiores placeat inventore doloremque ipsam architecto. Praesentium beatae commodi, temporibus aspernatur ipsam quibusdam accusamus vitae, ducimus quo quidem repellendus, dolores voluptate maiores? Velit recusandae blanditiis officiis, libero amet nostrum sunt, molestiae sit eius aperiam commodi fugit, qui ab optio? Esse velit, explicabo ex perspiciatis debitis molestiae dignissimos, hic nobis consectetur eum quis ab quod optio!</h3>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
            <ImgComp></ImgComp>
        </>
    )
}
export default Home